### ISSUE TITLE
Объединить команду на запрос в группу

### ISSUE THREAD

**Issue by dariy-rised** [ArtemGameDev/SquadSystem#2]
Объединить команду на запрос в группу с командой выше (на приглашение и на вступление одна команда должна быть)

**Comment by ArtemGameDev** [comment]
В плане? Ты имеешь ввиду ситуацию с 4 слотами - приглашениями?

**Comment by dariy-rised** [comment]
Ну типа просто одна команда чтобы была на приглашение и все.
Суммарно по факту какие команды:
1. Приглашение игрока напротив
2. Принять приглашение
3. Отклонить приглашение
4. Выйти из отряда
