### ISSUE TITLE
У тебя все операции делаются на клиенте

### ISSUE THREAD

**Issue by dariy-rised** [ArtemGameDev/SquadSystem#5]
У тебя считай аддон работает только у одного игрока, так как все обрабатывается на клиенте.
А точнее они делаются в Shared, хотя файл у тебя назван как клиентский, странно.
А по хорошему нужно разделять серверные функции от клиентских, почитай про net. библиотеку.

**Comment by ArtemGameDev** [comment]
Что ты предлагаешь?

**Comment by dariy-rised** [comment]
Пока пойми такую архитектуру:
autorun/server/ - путь, который читает только сервер
autorun/client/ - путь, который читает только клиент
autorun/ -  путь, который читают и сервер и клиент, то есть sh = shared
cl = client
sv = server
