### ISSUE TITLE
Оптимизация

### ISSUE THREAD

**Issue by dariy-rised** [ArtemGameDev/SquadSystem#7]
https://github.com/ArtemGameDev/SquadSystem/blob/ddc9fb48630841455dffbfa94a31d87c6857248e/SquadSystem/lua/autorun/cl_SquadSystem.lua#L106

и не только, вот еще нашел
https://github.com/ArtemGameDev/SquadSystem/blob/ddc9fb48630841455dffbfa94a31d87c6857248e/SquadSystem/lua/autorun/cl_SquadSystem.lua#L213

Тут нежелательно делать цикл по всем игрокам, подумай как это можно сделать без этого?
Ведь у тебя в ply:GetNWEntity("SquadMember01") 2,3,4 итак содержится энтити-игрок, зачем тебе его искать?

**Comment by ArtemGameDev** [comment]
А как? Тогда можно будет добавлять и тех, кто в других группах
